name: Merge Files to Markdown

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run merge script
        run: |
          npm install
          node merge-files.cjs

      - name: Commit merged file
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'Jarryd'
          git config --global user.email 'j@rryd.au'
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add copilot.md
          git commit -m "Auto-merged files into markdown"
          git push

