name: Merge Files to Markdown

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run merge script
        run: |
          npm install
          node merge-files.js

      - name: Commit merged file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add merged.md
          git commit -m "Auto-merged files into markdown"
          git push
