name: Merge Files to Markdown

on:
  workflow_dispatch:

# Add this permissions block
permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run merge script
        run: |
          npm install
          node merge-files.cjs

      # Simplified commit step
      - name: Commit merged file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add copilot.md
          git commit -m "Auto-merged files into markdown"
          git push